"""initial migration

Revision ID: 064abb086a27
Revises: edd631287828
Create Date: 2021-04-24 15:44:21.745612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '064abb086a27'
down_revision = 'edd631287828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
