"""sixth migration

Revision ID: 105a1a97c271
Revises: 18f6016f345c
Create Date: 2021-04-25 16:18:25.027908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '105a1a97c271'
down_revision = '18f6016f345c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_user_id_fkey', 'comments', type_='foreignkey')
    op.drop_column('comments', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('comments_user_id_fkey', 'comments', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
