"""fourth  migration

Revision ID: a20c75e5b321
Revises: c10d49071ea5
Create Date: 2021-04-24 18:15:16.456535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a20c75e5b321'
down_revision = 'c10d49071ea5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_pitch_date_posted'), 'pitch', ['date_posted'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pitch_date_posted'), table_name='pitch')
    # ### end Alembic commands ###
