"""third  migration

Revision ID: c10d49071ea5
Revises: 699d82226187
Create Date: 2021-04-24 17:53:37.816042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c10d49071ea5'
down_revision = '699d82226187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('pitch', sa.Text(), nullable=True))
    op.drop_column('pitch', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('pitch', 'pitch')
    # ### end Alembic commands ###
